#ifndef USER_H
#define USER_H

#include <string>
#include "database.h"

class User {
private:
    std::string username;
    std::string password;
    std::string email; 
    std::string name; 
    bool isAutoGenerated;

public:
    // Constructor
    User(const std::string& uname, const std::string& pwd, bool isAuto = false, const std::string& email = "", const std::string& name = "");

    // Getters
    std::string getUsername() const;
    std::string getPassword() const;
    std::string getEmail() const;
    bool IsAuto() const;
    std::string getUserEmail(Database& db, const std::string& username); // lấy email hiện tại của người dùng "đang" đăng nhập

    // Utility
    static std::string hashPassword(const std::string& password);
    static std::string AutoGenerated();

    // Database interactions
    bool registerToDB(Database& db);
    bool validateNewUser(Database& db);
    bool loginFromDB(Database& db, const std::string& uname, const std::string& pwd);
    bool changePassword(Database& db, const std::string& newPassword);
    
};

#endif // USER_H