#include "../include/ui.h"
#include "../include/user.h"
#include "../include/database.h"
#include "../otp/otp.h"
#include <windows.h>
#include <bits/stdc++.h>

using namespace std;

void enableVirtualTerminal() {
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    DWORD dwMode = 0;
    GetConsoleMode(hOut, &dwMode);
    dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
    SetConsoleMode(hOut, dwMode);
}

bool verifyOTPAndRegister(User& user, Database& db, const string& email, const string& username) {
    string otp = createOTP(email);
    if (otp.empty()) {
        cerr << "Unable to generate or send OTP." << endl;
        return false;
    }

    while (true) {
        string user_input;
        cout << "Enter the OTP code you received: ";
        getline(cin, user_input);
        if (user_input == otp) {
            cout << "Verification successful!" << endl;
            user.registerToDB(db);
            if (db.createWalletForUser(username)) {
                cout << "Wallet created.\n";
            } else {
                cerr << "Failed to create wallet.\n";
            }
            return true;
        } else {
            system("cls");
            cout << "Verification failed. Incorrect OTP. Please try again." << endl;
        }
    }
}

int main() {
    enableVirtualTerminal();
    Database db;
    string currentUsername;

    if (!db.connect("data/users.db")) {
        showMessage("Failed to create or open database.");
        return 1;
    }
    if (!db.createViTienTable() || !db.createTransactionHistoryTable()) {
        showMessage("Failed to create required tables.");
        return 1;
    }

    while (true) {
        showMenu();
        char choice = getMenuChoice();
        system("cls");

        if (choice == '1') {
            showLoginScreen();
            string username = getInput("Enter your username: ");
            string password = getInput("Enter your password: ");

            User tempUser("", "", false);
            if (tempUser.loginFromDB(db, username, password)) {
                currentUsername = username;
                showMessage(">> LOGIN SUCCESSFUL <<");
                db.showBalance(currentUsername);
                system("pause"); system("cls");
            } else {
                showMessage(">> LOGIN FAILED. Returning to main menu.");
                system("pause"); system("cls");
                continue;
            }
        } else if (choice == '2') {
            while (true) {
                showRegisterScreen();
                string username = getInput("Enter a username: ");
                string password = getInput("Enter a password: ");
                string email = getInput("Enter your email: ");
                string name = getInput("Enter your full name: ");

                User newUser(username, password, false, email, name);
                if (newUser.validateNewUser(db)) {
                    if (verifyOTPAndRegister(newUser, db, email, username)) {
                        showMessage(">>> ACCOUNT CREATED SUCCESSFULLY <<<");
                        cout << "Your account number is: " << newUser.getAccountNumber() << endl;
                        system("pause"); system("cls");
                        break;
                    }
                } else {
                    showMessage("Invalid input or username already exists.");
                    system("pause"); system("cls");
                }
            }
        } else if (choice == '3') {
            showRegisterScreenForMnger();
            while (true) {
                string adminPassword = getInput("Enter admin password: ");
                if (adminPassword == "admin123") {
                    system("cls");
                    break;
                } else {
                    showMessage("WRONG ADMIN PASSWORD.");
                    system("pause"); system("cls");
                }
            }

            string username = getInput("Enter username: ");
            string email = getInput("Enter email: ");
            string autoPassword = User::AutoGenerated();
            User newUser(username, autoPassword, true);

            if (newUser.validateNewUser(db)) {
                if (verifyOTPAndRegister(newUser, db, email, username)) {
                    showMessage("Manager created! Auto password: " + autoPassword);
                    system("pause"); system("cls");
                }
            } else {
                showMessage("Invalid input or username already exists.");
                system("pause"); system("cls");
            }
        }

        while (!currentUsername.empty()) {
            User temp("", "", false);
            string userEmail = temp.getUserEmail(db, currentUsername);
            string accNum = db.getAccountNumber(currentUsername);

            cout << "\033[1;36m═══════════════════════════════════════════════════════════\033[0m\n";
            cout << "\033[1;36m   🧾 ACCOUNT INFORMATION\033[0m\n";
            cout << "   \033[1;33m👤 Username:    \033[0;97m" << currentUsername << "\033[0m\n";
            cout << "   \033[1;33m📧 Email:       \033[0;97m" << userEmail << "\033[0m\n";
            cout << "   \033[1;33m💳 Account No.: \033[0;97m" << accNum << "\033[0m\n";
            cout << "\033[1;36m═══════════════════════════════════════════════════════════\033[0m\n\n";

            showTransactionMenu();
            char transactionChoice = getMenuChoice();
            system("cls");

            if (transactionChoice == '1') {
                showChanginPassScreen();
                while (true) {
                    string currentPassword = getInput("Enter current password: ");
                    User tempUser("", "", false);
                    if (tempUser.loginFromDB(db, currentUsername, currentPassword)) {
                        string email = tempUser.getUserEmail(db, currentUsername);
                        string otp = createOTP(email);
                        string input;
                        cout << "Enter OTP: "; getline(cin, input);
                        if (input != otp) {
                            showMessage("Incorrect OTP."); continue;
                        }
                        string newpass = getInput("Enter new password: ");
                        User user(currentUsername, newpass, false);
                        if (user.changePassword(db, newpass)) {
                            showMessage(">> PASSWORD CHANGED SUCCESSFULLY <<");
                            break;
                        } else {
                            showMessage("Failed to change password.");
                        }
                    } else {
                        showMessage("Wrong password.");
                    }
                    system("pause"); system("cls");
                }
            } else if (transactionChoice == '2') {
                showMessage(">> TRANSFER MONEY <<");
                string receiverAcc = getInput("Enter recipient's account number: ");
                string receiver = db.getUsernameByAccount(receiverAcc);
                if (receiver.empty()) {
                    showMessage(">> Invalid account number <<");
                    system("pause"); system("cls"); continue;
                }
                string senderEmail = temp.getUserEmail(db, currentUsername);
                string otp = createOTP(senderEmail);
                string inputOtp;
                cout << "Enter OTP to confirm transfer: "; getline(cin, inputOtp);
                if (inputOtp != otp) {
                    showMessage("Incorrect OTP. Transfer cancelled.");
                    system("pause"); system("cls"); continue;
                }
                double amount = stod(getInput("Enter amount to transfer: "));
                if (db.transferMoney(currentUsername, receiver, amount)) {
                    cout << "\033[1;32m";
                    cout << "╔════════════════════════════════════════════╗\n";
                    cout << "║           💸 TRANSFER SUCCESSFUL!         ║\n";
                    cout << "╠════════════════════════════════════════════╣\n";
                    cout << "║ 🔁 From   : " << setw(30) << left << currentUsername << "║\n";
                    cout << "║ 🎯 To     : " << setw(30) << left << receiver << "║\n";
                    cout << "║ 💵 Amount : " << setw(22) << left << (to_string((int)amount) + " VND") << "║\n";
                    cout << "╚════════════════════════════════════════════╝\n";
                    cout << "\033[0m";
                } else {
                    showMessage(">> TRANSFER FAILED <<");
                }
                system("pause"); system("cls");
            } else if (transactionChoice == '3') {
                double balance = db.getBalance(currentUsername);
                string formatted = formatCurrency(balance);
                printHeader("ACCOUNT BALANCE");
                cout << "\033[1;32m";
                cout << "\n   Your current balance is:\n\n";
                cout << "   ╔═══════════════════════════════════════╗\n";
                cout << "   ║     " << setw(20) << right << formatted << "     ║\n";
                cout << "   ╚═══════════════════════════════════════╝\n";
                cout << "\033[0m";
                system("pause"); system("cls");
            } else if (transactionChoice == '4') {
                auto history = db.getTransactionHistory(currentUsername);
                cout << "=== Lịch sử giao dịch của " << currentUsername << " ===\n";
                cout << "Thời gian          | Loại giao dịch | Số tiền   | Đối tác\n";
                cout << "----------------------------------------------------------\n";
                for (const auto& [datetime, type, amount, partner] : history) {
                    cout << datetime << " | " << type << " | " << amount << " VND | " << partner << '\n';
                }
                system("pause"); system("cls");
            } else if (transactionChoice == '5') {
                currentUsername = "";
                showMessage(">> LOGGED OUT <<");
                system("pause"); system("cls");
                break;
            }
        }
    }

    return 0;
}