#include "../include/user.h"
#include <iostream>
#include <ctime>
#include <cstdlib>
#include <sstream>
#include <functional>
#include "../include/ui.h"
#include "user.h"

using namespace std;

User::User(const string& uname, const string& pwd, bool isAuto, const string& mail, const string& name)
    : username(uname), password(pwd), email(mail), isAutoGenerated(isAuto), name(name), accountNumber(generateRandomAccountNumber()) {}

string User::getUsername() const { return username; }
string User::getPassword() const { return password; }
string User::getEmail() const { return email; }
bool User::IsAuto() const { return isAutoGenerated; }
string User::getAccountNumber() const { return accountNumber; }

string User::hashPassword(const string& password) {
    hash<string> hasher;
    return to_string(hasher(password));
}

string User::AutoGenerated() {
    const string chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    string password;
    srand(time(0));
    for (int i = 0; i < 10; ++i) {
        password += chars[rand() % chars.length()];
    }
    return password;
}

bool User::validateNewUser(Database& db) {
    if (username.find(" ") != string::npos || password.find(" ") != string::npos)
        return false;

    if (db.userExists(username)) return false;

    return true;
}

bool User::registerToDB(Database& db) {
    string hashed = hashPassword(password);
    return db.insertUser(username, hashed, isAutoGenerated, email, name, accountNumber);
}

bool User::loginFromDB(Database& db, const string& uname, const string& pwd) {
    string hashed = hashPassword(pwd);
    int isAuto = -1;
    if (db.validateUser(uname, hashed, isAuto)) {
        if (isAuto == 0) return true;

        while (true) {
            string newPass = getInput("Please enter your new password: ");
            User user(uname, newPass, false);
            if (user.changePassword(db, newPass)) break;
            showMessage("Invalid input!\n");
        }
        return true;
    }
    return false;
}

// bool User::loginFromDB(Database& db, const string& uname, const string& pwd) {
//     string hashed = hashPassword(pwd);
//     int dummy = -1; // giữ cho đúng tham số, dù không dùng IS_MANANGER
//     return db.validateUser(uname, hashed, dummy);
// }
    

bool User::changePassword(Database& db, const string& newPassword) {
    if (newPassword.find(" ") != string::npos) return false;

    string hashed = hashPassword(newPassword);
    return db.updatePassword(username, hashed);
}

string User::getUserEmail(Database& db, const string& username) {
    string sql = "SELECT EMAIL FROM USERS WHERE USERNAME = ?;";
    sqlite3_stmt* stmt;
    string email;

    if (sqlite3_prepare_v2(db.getDB(), sql.c_str(), -1, &stmt, nullptr) == SQLITE_OK) {
        sqlite3_bind_text(stmt, 1, username.c_str(), -1, SQLITE_STATIC);
        if (sqlite3_step(stmt) == SQLITE_ROW) {
            const unsigned char* storedEmail = sqlite3_column_text(stmt, 0);
            email = storedEmail ? reinterpret_cast<const char*>(storedEmail) : "";
        }
        sqlite3_finalize(stmt);
    } else {
        cerr << "Failed to prepare email query: " << sqlite3_errmsg(db.getDB()) << endl;
    }

    return email;
}

// Hàm sinh số tài khoản ngẫu nhiên 10 chữ số
string generateRandomAccountNumber() {
    srand(time(0));
    string accNum;
    for (int i = 0; i < 10; ++i) {
        accNum += to_string(rand() % 10);
    }
    return accNum;
}

bool User::isValidGmail(const string& email) {
    const string gmailSuffix = "@gmail.com";

    if (email.empty()) {
        cout << "Invalid input: email is empty.\n";
        return false;
    }

    if (email.length() < gmailSuffix.length() ||
        email.compare(email.length() - gmailSuffix.length(), gmailSuffix.length(), gmailSuffix) != 0) {
        cout << "Invalid input: email must end with '@gmail.com'.\n";
        return false;
    }

    return true;
}

bool User::changeName(Database& db, const string& newName) {
    if (newName.empty()) return false;

    return db.updateName(username, newName);
}